---
#hostname: rds-PR601-VR603
server:
   cacaca:
      hostname: 'lxdv324a.unix-int.intra-int.bdf-int.local'
      user: 'i2162eh'
      password: 'Rdsba94*'
   b:
      hostname: 'lxdv324a.unix-int.intra-int.bdf-int.local'
      user: 'i2162eh'
      password: 'Rdsba94*'
